source 'http://rubygems.org'

group :jekyll_plugins do
  gem 'jekyll'
  gem 'jekyll-admin'
  gem 'jekyll-paginate'
  gem 'wdm', '>= 0.1.0' if Gem.win_platform?
  gem 'support-for'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-feed'
  gem 'jekyll-gist'
  gem 'jekyll-mentions'
  gem 'jekyll-coffeescript'
  gem 'jekyll-redirect-from'
  gem 'jekyll-sass-converter'
  gem 'jekyll-archives'
  gem 'jekyll-jupyter-notebook'
  gem 'jekyll-include-cache'
  gem 'kramdown'
  gem 'liquid'
  gem 'rouge'
  gem 'jemoji'
  gem 'sass'
  gem 'safe_yaml'
#  gem 'jekyll-livereload'
 end
